### ISSUE TITLE
TypeError: Cannot read property 'Value' of undefined

### ISSUE THREAD

**Issue by tobintax** [ldittmar81/ioBroker.fronius#20]
Seit dem Update auf 1.0.3 kommt es zu folgenden Warnings im Adapter Log: 

TypeError: Cannot read property 'Value' of undefined

**Comment by tobintax** [comment]
@ldittmar81

**Comment by iotathome** [comment]
Ich kann das Problem bestätigen.

**Comment by Hansi1989** [comment]
Hallo bin von eine Raspberry auf einen Docker umgezogen und habe seit heute das gleiche Problem.
Muss aber auch dazu sagen ich habe heute ein Firmwareupdate beim Wechselrichter gemacht Softwareversion 3.16.7-1
Kann mir jemand helfen?

Mit freundlichen grüßen
Hansi
